sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

script:
  - set -e
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose -f "docs/postgresql/docker-compose.yml" pull
  - docker-compose -f "docs/postgresql/docker-compose.yml" start
  - docker ps
  - npm test
  - npm run eslint
  - docker build -t "blutner/ocomis-user-api:latest" .
  - docker tag "blutner/ocomis-user-api:latest" "blutner/ocomis-user-api:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-user-api:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-user-api:latest"
  - docker logout
